### ISSUE TITLE
Release 1.1.2 TypeError: queue.getName is not a function

### ISSUE THREAD

**Issue by sbarzaghialteaup** [vcapretz/bull-board#193]
Hi,

After updating from release 1.0.1 to 1.1.2 I get the error:
```
TypeError: queue.getName is not a function
    at monitor/node_modules/bull-board/dist/index.js:36:28
```
I solved using the new `BullAdapter` class.
Is the release 1.1.2 not backwards compatible?

Thank
Sam

**Comment by felixmosh** [comment]
Yeah, we decided to bump minor instead of major since the major release is "new".
Probably not the so semantic of us, sorry for that 😅

**Comment by kyleolsondesign** [comment]
Sorry, what is the solution here? I'm using latest BullMQ (`1.11.2`) and latest bull-board (`1.1.2`) and it's not working out-of-the-box...

**Comment by felixmosh** [comment]
The solution is to wrap the queue with the relevant adapter
